### PR TITLE
Added best practices and features

### PR DESCRIPTION
**Pull request by agmbk**

### CODE REVIEW

**Comment by agmbk** [comment]
I think you are missing a valid API key in your CI CD. Just saying because I plan to contribute to a fair amount to this repo in the next days and don't want to bother you with a lot of merge requests.

**Comment by agmbk** [comment]
Hum I guess it all went in the same pull request, I'm not really good at this :).

**Comment by jdrouet** [comment]
Thanks for all this! I've to find a way to fix those tests...

**Comment by agmbk** [comment]
I decided to make the effort to contribute instead of just adding the features on my own project. Definitely more to come as I discover edge cases or need missing api routes.

**Comment by jdrouet** [comment]
Thanks for that, I'll do my best to review your work ☺️

**Pull request merged**
