### PR TITLE
feat: create a Client constructor to supply the Reqwest::Client

### PR DESCRIPTION
**Pull request by fusetim**
Create a new constructor `with_http_client` for `tmdb_api::client::Client` to supply the inner `Reqwest::Client`.

I'm not sure the name is well chosen, given the existence of `with_base_url`, which doesn't follow the same model. Nevertheless, I think it's the only blocking issue with this PR.

Resolve: https://github.com/jdrouet/tmdb-api/issues/35

### CODE REVIEW

**Comment by jdrouet** [comment]
👋 Thanks @fusetim for this PR.
After thinking about it, I think I'd have went with a builder pattern.

**Comment by fusetim** [comment]
Thank you for your reply. 
Would this new approach suit you?

**Comment by jdrouet** [comment]
I did a fix and a cleanup PR in #37 😉

**Comment by fusetim** [comment]
Amazing, thank you 🎉

**Pull request closed without merging**
